server:
  port: 8761
spring:
  application:
      name: EUREKA-SEVER
  security:
      user:
        name: liuyang19900520
        password: 123456
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}

    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 7

  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://liuyang19900520:123456@localhost:8761/eureka
